FROM python:3.9-slim

RUN apt-get update && apt-get install -y python3-pip

RUN useradd --create-home myuser
WORKDIR '/home/myuser'
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

USER myuser

EXPOSE 5000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]